---
- hosts: all
  gather_facts: no
  connection: local

  tasks:
    - name: Upload file
      local_action:
        module: ftp
        host: ***IP***
        user: ***ftp_user***
        password: ***ftp_password***
        src: file.txt
        dest: file.txt
        command: put
      changed_when: false
      register: out

    - debug:
        msg: "{{ out }}"
